service: s3-prefix-experiment

frameworkVersion: '2 || 3'
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: npm
    excludeFiles: src/**/*.test.js

functions:
  handler:
    handler: src/handler.default
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - s3:PutObject        
        Resource: "arn:aws:s3:::*"
    events:
      - http:
          path: /
          method: get
    environment:
      S3_BUCKET:
        Ref: S3Bucket

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        VersioningConfiguration:
          Status: Enabled