service: serverless-typescript

frameworkVersion: 2
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

package:
  individually: true

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: npm
    excludeFiles: src/**/*.test.js

functions:
  handler:
    handler: src/handler.default
    events:
      - http:
          path: /
          method: get

# resources:
#   Resources:
#     SuperSweetStream:
#       Type: AWS::Kinesis::Stream
#       Properties:
#         Name: kdg-solution-1-stream
#         RetentionPeriodHours: 24
#         ShardCount: 3